export const US_CITIES: string[] = [
  "Adairsville, GA",
  "Akron, OH",
  "Albany, GA",
  "Alexandria, VA",
  "Aliquippa, PA",
  "Alma, AR",
  "Arlington Heights, IL",
  "Ashland, VA",
  "Athens, TN",
  "Atlanta, GA",
  "Austin, TX",
  "Avenel, NJ",
  "Avondale, PA",
  "Ballston Lake, NY",
  "Baltimore, MD",
  "Barnesville, PA",
  "Bartlett, IL",
  "Baton Rouge, LA",
  "Battle Creek, MI",
  "Bay City, MI",
  "Bay Shore, NY",
  "Bedford, OH",
  "Belgium, WI",
  "Beltsville, MD",
  "Bensalem, PA",
  "Bensenville, IL",
  "Berthoud, CO",
  "Bethel, PA",
  "Biloxi, MS",
  "Birmingham, AL",
  "Blauvelt, NY",
  "Bluffton, IN",
  "Boston, MA",
  "Boswell, IN",
  "Bowling Green, KY",
  "Bradner, OH",
  "Brewster, NY",
  "Bridgeton, MO",
  "Bridgeton, NJ",
  "Bridgewater, NJ",
  "Bronx, NY",
  "Brooklyn, NY",
  "Burien, WA",
  "Burlingame, CA",
  "Byron Center, MI",
  "Calumet City, IL",
  "Cambridge, MD",
  "Carlisle, PA",
  "Carlstadt, NJ",
  "Carrollton, TX",
  "Carson, CA",
  "Carteret, NJ",
  "Caruthers, CA",
  "Centerville, AL",
  "Central Islip, NY",
  "Cerritos, CA",
  "Chalfont, PA",
  "Charlotte, NC",
  "Cheektowaga, NY",
  "Chesapeake, VA",
  "Cheshire, CT",
  "Chicago, IL",
  "Church Point, LA",
  "Cincinnati, OH",
  "Clearwater, NE",
  "Clemmons, NC",
  "Cleveland, OH",
  "Cleveland, TN",
  "Clifton, NJ",
  "Commerce, GA",
  "Compton, CA",
  "Congers, NY",
  "Conroe, TX",
  "Cookeville, TN",
  "Coopersville, MI",
  "Corpus Christi, TX",
  "Covington, OH",
  "Cranbury, NJ",
  "Culpeper, VA",
  "Cumberland, MD",
  "Dallas, TX",
  "Dalton, GA",
  "Darlington, SC",
  "Dayton, NJ",
  "Deer Park, TX",
  "Delaware, OH",
  "Deming, NM",
  "Denver, CO",
  "Des Plaines, IL",
  "Doral, FL",
  "Douglas, GA",
  "Douglasville, GA",
  "Dover, DE",
  "Dover, NJ",
  "Dunn, NC",
  "East Grand Forks, MN",
  "East Syracuse, NY",
  "Eastampton, NJ",
  "Eau Claire, WI",
  "Edison, NJ",
  "Edmond, OK",
  "Elizabethton, TN",
  "Elk Grove Village, IL",
  "Elkton, MD",
  "Englewood, NJ",
  "Ephrata, PA",
  "Erie, PA",
  "Euclid, OH",
  "Everett, MA",
  "Exton, PA",
  "Fair Lawn, NJ",
  "Fairburn, GA",
  "Fairdale, KY",
  "Fairfield, CA",
  "Fairfield, NJ",
  "Fairless Hills, PA",
  "Flagstaff, AZ",
  "Flint, MI",
  "Florence, AL",
  "Forest Park, GA",
  "Fort Worth, TX",
  "Fountain Run, KY",
  "Franklin Park, IL",
  "Frederick, MD",
  "Friendsville, TN",
  "Gainesville, FL",
  "Gainesville, GA",
  "Gambier, OH",
  "Garner, NC",
  "Geneva, IL",
  "Gibbstown, NJ",
  "Glen Burnie, MD",
  "Goose Creek, SC",
  "Gouldsboro, PA",
  "Grand Prairie, TX",
  "Grand Rapids, MI",
  "Greencastle, IN",
  "Greensboro, NC",
  "Greenville, NC",
  "Greenville, TX",
  "Grove City, OH",
  "Guilderland Center, NY",
  "Hagerstown, MD",
  "Haines City, FL",
  "Hamilton, OH",
  "Hammond, IN",
  "Hanover, MD",
  "Hanover, PA",
  "Harrisburg, PA",
  "Hauppauge, NY",
  "Hazelton, PA",
  "Hermitage, PA",
  "Hickory, NC",
  "High Point, NC",
  "Holly Hill, FL",
  "Houston, TX",
  "Hudson, NY",
  "Hudson, WI",
  "Huntingdon, TN",
  "Huntington, IN",
  "Hurlock, MD",
  "Hyattsville, MD",
  "Indian Trail, NC",
  "Indianapolis, IN",
  "Iowa City, IA",
  "Itasca, IL",
  "Jacksonville, FL",
  "Janesville, WI",
  "Jersey City, NJ",
  "Johnson City, TN",
  "Johnstown, NY",
  "Kansas City, KS",
  "Kearny, NJ",
  "Keyport, NJ",
  "Kinloch, MO",
  "Knoxville, TN",
  "Lafayette, LA",
  "Lancaster, NY",
  "Lancaster, PA",
  "Laredo, TX",
  "Las Vegas, NV",
  "Lawrence, MA",
  "Leighton, AL",
  "Levittown, PA",
  "Lewisville, TX",
  "Lexington, KY",
  "Lincolnton, NC",
  "Linden, NJ",
  "Lindenhurst, NY",
  "Lindenwold, NJ",
  "Linwood, NC",
  "Lithia Springs, GA",
  "Lone Oak, TX",
  "Long Island City, NY",
  "Longwood, FL",
  "Loris, SC",
  "Los Banos, CA",
  "Loudon, TN",
  "Louisville, KY",
  "Lynchburg, VA",
  "Lyons, IL",
  "Madisonville, KY",
  "Maryville, TN",
  "Maspeth, NY",
  "Mc Kinney, TX",
  "Mcdonough, GA",
  "Mebane, NC",
  "Medley, FL",
  "Merrillville, IN",
  "Metuchen, NJ",
  "Miami Gardens, FL",
  "Miami, FL",
  "Millersburg, OH",
  "Millington, TN",
  "Milton, WI",
  "Milwaukie, OR",
  "Minooka, IL",
  "Mishawaka, IN",
  "Missouri City, TX",
  "Modesto, CA",
  "Montgomery, NY",
  "Mount Holly, NJ",
  "Mount Pleasant, TN",
  "Mount Vernon, NY",
  "Muscle Shoals, AL",
  "Nashville, TN",
  "New Bedford, MA",
  "New Paltz, NY",
  "Newark, CA",
  "Newark, NJ",
  "Newport News, VA",
  "North Brunswick Township, NJ",
  "North Las Vegas, NV",
  "North Little Rock, AR",
  "Northfield, MN",
  "Northumberland, PA",
  "Oakdale, CA",
  "Oakdale, PA",
  "Oakland, CA",
  "Ocala, FL",
  "Oceanside, NY",
  "Oconomowoc, WI",
  "Oklahoma City, OK",
  "Opa Locka, FL",
  "Orangeburg, SC",
  "Orlando, FL",
  "Owensboro, KY",
  "Paramount, CA",
  "Parsippany, NJ",
  "Paterson, NJ",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Piedmont, SC",
  "Pierson, FL",
  "Piscataway, NJ",
  "Pitman, NJ",
  "Pittston, PA",
  "Pixley, CA",
  "Plainfield, IN",
  "Plano, TX",
  "Plattsburgh, NY",
  "Pooler, GA",
  "Port Saint Lucie, FL",
  "Portland, OR",
  "Pottsville, PA",
  "Punta Gorda, FL",
  "Raleigh, NC",
  "Reading, PA",
  "Renovo, PA",
  "Richmond, VA",
  "Ridgefield, NJ",
  "Riviera Beach, FL",
  "Rochelle, IL",
  "Rochester, NY",
  "Rockingham, VA",
  "Rocky Mount, NC",
  "Romeoville, IL",
  "Romulus, MI",
  "Sacramento, CA",
  "Saginaw, TX",
  "Saint Bernard, OH",
  "Saint Charles, MO",
  "Saint Henry, OH",
  "Saint Louis, MO",
  "Salisbury, MD",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Jose, CA",
  "San Leandro, CA",
  "Santa Clarita, CA",
  "Santa Fe Springs, CA",
  "Saratoga Springs, NY",
  "Savannah, GA",
  "Sayreville, NJ",
  "Schenectady, NY",
  "Scottsboro, AL",
  "Scranton, PA",
  "Seattle, WA",
  "Secaucus, NJ",
  "Selma, NC",
  "Shelbyville, TN",
  "Smyrna, GA",
  "South Bend, IN",
  "South San Francisco, CA",
  "Springboro, OH",
  "Springfield, MA",
  "Springfield, OH",
  "Statesville, NC",
  "Stockton, CA",
  "Streetsboro, OH",
  "Sturbridge, MA",
  "Suffield, CT",
  "Suffolk, VA",
  "Superior, WI",
  "Swedesboro, NJ",
  "Sylmar, CA",
  "Syracuse, NY",
  "Tamaqua, PA",
  "Tampa, FL",
  "Thornton, CA",
  "Tiffin, OH",
  "Toledo, OH",
  "Tolleson, AZ",
  "Totowa, NJ",
  "Towanda, PA",
  "Tullahoma, TN",
  "Union City, CA",
  "Upper Marlboro, MD",
  "Urbana, IL",
  "Utica, NY",
  "Van Buren, MO",
  "Vancouver, WA",
  "Vernon, CA",
  "Vinita Park, MO",
  "Vinita, OK",
  "Walnut, CA",
  "Washington, DC",
  "Watertown, WI",
  "Watkins Glen, NY",
  "West Warwick, RI",
  "Westlake, OH",
  "Westland, MI",
  "Whitehall, NY",
  "Wilkes Barre, PA",
  "Williamston, SC",
  "Winchester, VA",
  "Windsor Locks, CT",
  "Wingdale, NY",
  "Woodward, IA",
  "York, PA",
  "Youngstown, OH",
];